[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE = "https://finbank-141j.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
